server:
  port: 8081
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http:localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeader: "*"
      routes:
        - id: auth-service
          uri: http://localhost:9000
          predicates:
              - Path=/api/auth/**

        - id: product-service
          uri: http://localhost:9100
          predicates:
            - Path=/api/products/**
          filters:
            - RequestRateLimiter
            - name: CircuitBreaker
              args:
                name: productServiceCircuitBreaker
                fallbackUri: forward:/fallback/product

        - id: cart-service
          uri: http://localhost:9200
          predicates:
            - Path=/api/carts/**

        - id: order-service
          uri: http://localhost:9300
          predicates:
            - Path=/api/orders/**

        - id: payment-service
          uri: http://localhost:9400
          predicates:
            - Path=/api/payments/**
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenish-rate: 10
            redis-rate-limiter.burst-capacity: 20
            redis-rate-limiter.requestedTokens: 1
        - AddResponseHeader=X-Gateway-Response, Passed-through-API-Gateway
        - AddRequestHeader=X-Response-Time, ${date}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
        probability: 1.0
  zipkin:
    base-url: http://zipkin:9411